version: "3"

services:
  postgres:
    image: postgres:14.0
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: catalog_db_password
      POSTGRES_USER: catalog_db
      POSTGRES_DB: catalog_service
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
